name: FTP Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  ftp-deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy to FTP Server
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        ftp-server: ftp://104.250.128.229
        ftp-username: modhu
        ftp-password: ${{ secrets.FTP_PASSWORD }}